# Generated by Django 6.0 on 2025-12-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedChat',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
