# Generated by Django 6.0.1 on 2026-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_job_notificationsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowedchat",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
