# Generated by Django 6.0.1 on 2026-02-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_allowedchat_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllowedChat",
            new_name="Chat",
        ),
        migrations.AddField(
            model_name="chat",
            name="status",
            field=models.CharField(choices=[("pending", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="chat",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
