# Generated by Django 6.0.1 on 2026-02-12 21:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_allowedchats_status_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsubscription',
            name='last_seen_game_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notificationsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('all', 'All Giveaways'), ('new_notify_empty', 'New Only (Notify When Empty)'), ('new_silent_empty', 'New Only (Silent When Empty)')], default='new_notify_empty', max_length=20),
        ),
    ]
