# Generated by Django 6.0 on 2026-01-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('last_run', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.TimeField()),
                ('enabled', models.BooleanField(default=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.allowedchat')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('enabled', True)), fields=['notification_time', 'enabled'], name='notif_time_enabled_true_idx')],
            },
        ),
    ]
